version: '3.8'

services:
  digital-sentry:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - PHP_DATE_TIMEZONE=Asia/Kolkata
    container_name: digital-sentry-ctf
    restart: unless-stopped